version: '3.9'

services:
  postgres:
    build: ./database/
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: always
    ports:
      - 6666:8080
